### ISSUE TITLE
Input CTRL+Directions

### ISSUE THREAD

**Issue by oniledio** [b-kaiser/ergotype#3]
Inputting CTRL+Direction keys will result in junk in the program input

**Comment by oniledio** [comment]
Same with ALT+Directions, SHIFT+Directions

**Comment by b-kaiser** [comment]
In order to fix this I need the junk that gets displayed. Until I have a proper parser for the input events (which might take some time) I can easily hotfix individual bugs like this. But only If I resize the letter combinations that appear in situations like this.

**Comment by oniledio** [comment]
The input CTRL+Left CTRL+Up CTRL+Right CTRL+Down results in: ;5D; 5A;5 C;5B 
the spaces in between seem to be arbitrary
